baseURL = "https://mingyue91.github.io/ming91/"
locale = "zh"
title = "min9's Blog"
theme = "stack"

paginate = 10
defaultContentLanguage = "zh"
enableEmoji = true
hasCJKLanguage = true

[permalinks]
  page = "/:slug/"

[params]
  description = "min9 的个人博客"
  mainSections = ["posts"]

  copyright = "© 2026 min9"

  [params.dateFormat]
    published = "2006-01-02"
    updated = "2006-01-02"

  [params.footer]
    since = 2026

  favicon = "/avatar.jpg"

  [params.opengraph.twitter]
    site = "mingyue91"
    card = "summary_large_image"

  [params.author]
    name = "min9"

  [params.sidebar]
    avatar = "/avatar.jpg"
    subtitle = "二次元 & 技术"

  [params.widgets]
    enabled = ["recent_posts", "tag_cloud", "archives"]

  [params.color]
    scheme = "auto"

[menu]
  [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/mingyue91"
    weight = 1
    [menu.social.params]
      Icon = "brand-github"
      newTab = true

  [[menu.social]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 2
    [menu.social.params]
      Icon = "rss"
      newTab = true

  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "归档"
    url = "/posts/"
    weight = 2

[taxonomies]
  category = "categories"
  tag = "tags"
